[package]
name = "welcomebot"
version = "0.1.1"
edition = "2021"
resolver = "2"

[workspace]
members = [".", "img-gen", "migration"]

[dependencies]
ab_glyph = "0.2.25"
img-gen = { path = "img-gen" }
image = "0.25.1"
poise = "0.6.1"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.7"
log = "0.4.21"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
reqwest = "0.12.4"
tempdir = "0.3.7"
uuid = { version = "1.8.0", features = ["v4"] }
thiserror = "1.0.63"
