[package]
name = "welcomebot"
version = "0.1.1"
edition = "2021"
resolver = "2"

[workspace]
members = [".", "entity", "img-gen", "migration", "service"]

[dependencies]
ab_glyph = "0.2.28"
img-gen = { path = "img-gen" }
image = "0.25.2"
poise = "0.6.1"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.7"
log = "0.4.22"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
reqwest = "0.12.7"
tempfile = "3.12.0"
uuid = { version = "1.10.0", features = ["v4"] }
thiserror = "1.0.63"
