[package]
name = "welcomebot"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = [".", "img-gen"]

[dependencies]
ab_glyph = "0.2.25"
img-gen = { path = "img-gen" }
image = "0.25.1"