[package]
name = "corelib"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
logforth = { version = "0.23.1", features = ["colored", "fastrace", "json", "rolling-file"] }
fastrace = "0.7.9"