//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "guild")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub guild_id: i64,
    pub welcome_settings_id: Option<i32>,
    pub create_user_id: i64,
    #[sea_orm(column_type = "Text")]
    pub create_date: String,
    pub modify_user_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub modify_date: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auto_ban_role::Entity")]
    AutoBanRole,
}

impl Related<super::auto_ban_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AutoBanRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
