//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "twitch_broadcaster")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub broadcaster_login: String,
    #[sea_orm(unique)]
    pub broadcaster_id: String,
    pub broadcaster_name: String,
    pub access_token: String,
    pub refresh_token: Option<String>,
    pub last_refreshed: Option<DateTimeUtc>,
    pub create_date: DateTimeUtc,
    pub modify_date: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
