//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "web_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub username: String,
    #[sea_orm(unique)]
    pub user_id: i64,
    pub access_token: Option<String>,
    pub last_refresh: Option<DateTime>,
    pub password: Option<String>,
    pub email: Option<String>,
    pub last_login_ip: Option<String>,
    pub twitch_broadcaster_id: Option<i32>,
    pub create_date: DateTime,
    pub modify_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
